name: flutter_spotify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.0.0
  url_launcher: ^6.1.11
  flutter_web_auth_2: ^2.1.4
  flutter_dotenv: ^5.1.0
  flutter_config: ^2.0.0

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  just_audio: ^0.9.34
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true